Add working webapp
dsc-iem/AI-Hacktoberfest pull request #16
Opened 2020-10-20 20:08 UTC by khanfarhan10

# Description
added files for deployment forest fire predictions using Flask. Hosted on pythonanywhere at http://kfpro.pythonanywhere.com/forestfirepreds

Fixes # [ISSUE]
solves creating a simple webapp #10

# Type of Change:
- Code for WebApp
- Documentation
- Working Demo

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
Deployed [here!](http://kfpro.pythonanywhere.com/forestfirepreds)

2020-10-21 19:10 UTC, Nibba2018 requested changes
Hey @khanfarhan10 , check my review below.

2020-10-21 19:10 UTC, Nibba2018 commented on webapp/PythonAnywhere_deployment_files/BashConsole.txt
> +
Add these instructions in a README.md file in this folder.

2020-10-21 19:10 UTC, Nibba2018 commented on webapp/PythonAnywhere_deployment_files/BashConsole.txt
> +remote: Enumerating objects: 20, done.
Replace your repo URL with AI-Hacktoberfest's URL.

2020-10-21 19:10 UTC, Nibba2018 commented on webapp/README.md
> +###### Also, for ML models you might want to change the requirements.txt file and add numpy, pandas, sklearn etc. to it.
Convert them to project references. Also mention the issues tab of AI-hacktoberfest instead of your personal email.

2020-10-21 19:10 UTC, Nibba2018 commented on webapp/templates/index.html
> +      <a href="https://github.com/khanfarhan10/ForestFirePredictionsFlaskPython">ForestFirePredictionsFlaskPython</a>
Replace these links

2020-10-21 19:10 UTC, Nibba2018 commented on webapp/templates/index.html
> +    <p>
Remove this copyright or create a dynamic page to display repo contributors.

2020-10-22 06:10 UTC, soumya997 commented
@Nibba2018 I would like to add some points if you don't mind.
1. I think @khanfarhan10 should use the already build model for prediction. I have provided a link at the bottom of my model building notebook to download the model.
2. And as a prediction it should give prediction on the amount of area that can burn not the probability of having a forest fire, and i'm saying this because the provide data don't allow to do that.
<center><img src="https://i.imgur.com/VfEeRAO.jpg" width="700px"></center>

2020-10-22 09:56 UTC, Nibba2018 commented
I Agree with @soumya997 . Maybe we can have a drop down menu to select different models built by different contributors. We already have access to the python scripts so generating the model shouldn't be a problem. Determining the burnt area is a better metric to calculate.

2020-10-24 20:22 UTC, khanfarhan10 commented
Agreed, but since I made this as an initial progress as a WebApp Template, we may further develop it. I didn't hardcode it to do all the stuff. Hope that solves queries @Nibba2018  @soumya997 and it is welcome for changes by all of you.

2020-10-24 20:22 UTC, closed without merging