added Bivariate Analysis
dsc-iem/AI-Hacktoberfest pull request #8
Opened 2020-09-30 20:01 UTC by Dsantra92

The notebook uploaded contains Bi-variate analysis of the features with the feature variables.

2020-10-01 07:36 UTC, Nibba2018 commented
Quick question @Dsantra92 , is this PR showing as an eligible contribution for hacktoberfest?

2020-10-01 11:09 UTC, Dsantra92 commented
@Nibba2018 it seems yes.
![image](https://user-images.githubusercontent.com/55111154/94802045-94eef280-0404-11eb-9e76-adf64bb44e44.png)

2020-10-01 14:37 UTC, Nibba2018 requested changes
Hello @Dsantra92 , Thank you for creating this PR. Great job with the analysis part. I have mentioned some typos below which applies to both the `.py` file and `.ipynb` files. Once they are fixed it will be ready to be merged.

2020-10-01 14:37 UTC, Nibba2018 commented on submissions/PythonScripts/bivariate_analysis.py
> +*   Apart from these months, majior forest fires occoured during July and March.
Typos: `occur`, `major`

2020-10-01 14:37 UTC, Nibba2018 commented on submissions/PythonScripts/bivariate_analysis.py
> +* Majiority of the forest fires occoured during August and September.These include majior forest fires and also very minimal forest fire.Forest fires during this month caused most damage to the fores
typo: `Majority`

2020-10-01 14:37 UTC, Nibba2018 commented on submissions/PythonScripts/bivariate_analysis.py
> +* Few forest fires were experienced March, April, June, October  experienced  but they were mostly calm.This is evident from the mean line of the box plot which in their case lies very close to zero.
The comment grammar can be improved.

2020-10-01 14:37 UTC, Nibba2018 commented on submissions/PythonScripts/bivariate_analysis.py
> +* We can spot an outlier in the first plot which shows there is a fire even when ther is rain.
typo: `there`

2020-10-02 04:47 UTC, Dsantra92 commented
@Nibba2018 I am sorry for those typos.I have fixed the typos you mentioned as well as some other mistakes I made, I hope it's okay now.

2020-10-02 06:37 UTC, Nibba2018 commented
@Dsantra92 It's okay typos happen, you don't have to be sorry about it :laughing:. So far LGTM. Merging!

2020-10-02 06:37 UTC, merged